name: Daily Market Bot

on:
  schedule:
    - cron: '0 3 * * *'   # Runs daily (UTC time)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      -  name: Install libraries
         run: |
          pip install yfinance pandas requests matplotlib

      - name: Run bot
        run: python market_bot.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
